const {JSDOM,VirtualConsole}=require(process.env.PITI_JSDOM_PATH||'jsdom');const fs=require('fs'),assert=require('assert/strict');
const html=fs.readFileSync('index.html','utf8').replace('const db=','let db=').replace('<script src="/vendor/supabase.min.js"></script>','').replace('render();maybeOpenJoinLink();initAuth();','window.testRun=code=>eval(code);render();');const errors=[],vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));const dom=new JSDOM(html,{url:'https://mypiti.online',runScripts:'dangerously',virtualConsole:vc,beforeParse(w){w.matchMedia=()=>({matches:false,addEventListener(){}});w.scrollTo=()=>{}}});
(async()=>{try{const w=dom.window,d=w.document;
w.testRun("window.record={content:clone(defaultAboutContent),version:1};db={rpc:async(name,args)=>{if(name==='save_about_content'){if(window.rejectSave)return {error:{message:'conflict'}};if(args.p_version!==window.record.version)throw Error('version mismatch');window.record={content:args.p_content,version:window.record.version+1}}return {data:clone(window.record)}}};view.innerHTML='<div id=editor></div>';renderAboutEditor(document.getElementById('editor'),window.record)");
d.querySelector('#aboutEdit-title').value='Yeni Hakkında';d.querySelector('#aboutEdit-intro').value='<img src=x onerror=alert(1)>\nYeni tanıtım';d.querySelector('#aboutEditor').dispatchEvent(new w.Event('input'));
assert.equal(d.querySelector('#aboutPreview img'),null);assert.match(d.querySelector('#aboutPreview').textContent,/<img/);assert.equal(w.record.version,1,'draft is not public');await d.querySelector('#aboutEditor').onsubmit({preventDefault(){}});assert.equal(w.record.version,2);assert.match(d.querySelector('#aboutSaveStatus').textContent,/Yayınlandı/);
for(const role of ['pt','member']){w.testRun(`adminMode=false;state.role='${role}';state.page='about';aboutPage()`);await w.testRun('refreshAboutContent()');assert.equal(d.querySelector('#sharedAboutContent h1').textContent,'Yeni Hakkında');assert.equal(d.querySelector('#sharedAboutContent img'),null)}
w.record={...w.record,version:3,content:{...w.record.content,title:'Canlı güncelleme'}};await w.testRun('refreshAboutContent()');assert.equal(d.querySelector('#sharedAboutContent h1').textContent,'Canlı güncelleme');
w.testRun("view.innerHTML='<div id=editor></div>';renderAboutEditor(document.getElementById('editor'),window.record);window.rejectSave=true");await d.querySelector('#aboutEditor').onsubmit({preventDefault(){}});assert.match(d.querySelector('#aboutSaveStatus').textContent,/Yayınlanamadı/);assert.equal(w.record.version,3);assert.equal(d.querySelector('#aboutEdit-title').disabled,false);
assert.deepEqual(errors,[]);console.log('PASS: safe preview, explicit publication, shared PT/member content, live refresh, version forwarding and failed-save handling');}finally{dom.window.close()}})().catch(e=>{console.error(e);process.exitCode=1});
