const {JSDOM,VirtualConsole}=require(process.env.PITI_JSDOM_PATH||'jsdom'),fs=require('fs'),assert=require('assert/strict');
(async()=>{const html=fs.readFileSync('index.html','utf8').replace('<script src="/vendor/supabase.min.js"></script>','').replace('render();maybeOpenJoinLink();initAuth();','window.testRun=code=>eval(code);render();maybeOpenJoinLink();initAuth();');let verified=false;const errors=[],vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));const dom=new JSDOM(html,{url:'https://mypiti.online',runScripts:'dangerously',virtualConsole:vc,beforeParse(w){w.matchMedia=()=>({matches:false,addEventListener(){}});w.scrollTo=()=>{};w.supabase={createClient:()=>({auth:{onAuthStateChange(){},getSession:async()=>({data:{session:null}}),mfa:{getAuthenticatorAssuranceLevel:async()=>({data:{currentLevel:verified?'aal2':'aal1'}}),listFactors:async()=>({data:{totp:[{id:'test',status:'verified'}]}}),challengeAndVerify:async({code})=>code==='123456'?(verified=true,{data:{}}):{error:{message:'Yanlış kod'}}}},rpc:async(name,args)=>{if(name==='app_settings')return {data:{registration_open:true}};if(name==='admin_console'){if(args.p_action==='overview')return {data:{users:1,trainers:1,clients:0,online:1}};return {data:[{id:'test',full_name:'Test <admin>',username:'test',role:'pt',email:'test@example.invalid',created_at:new Date().toISOString(),is_admin:true}]}}return {data:null}}})}}});const w=dom.window,d=w.document;await new Promise(r=>setTimeout(r,20));
assert.equal(d.querySelector('#registrationName').hidden,true);assert.equal(d.querySelector('#demoBtn').hidden,true);d.querySelector('#signUpBtn').click();assert.equal(d.querySelector('#registrationName').hidden,false);d.querySelector('#signUpBtn').click();
for(const id of ['authEmail','authPassword']){d.getElementById(id).value='DEMO';d.getElementById(id).dispatchEvent(new w.Event('input'))}assert.equal(d.querySelector('#demoBtn').hidden,false);d.querySelector('#authPassword').value='demo';d.querySelector('#authPassword').dispatchEvent(new w.Event('input'));assert.equal(d.querySelector('#demoBtn').hidden,true);
// Exercise session routing without loading real business data.
await w.testRun(`
 window.savedEnterAdmin=enterAdmin;window.savedCheck=checkAccountAccess;window.savedLoad=loadCloudData;
 window.adminEntries=0;window.accountEntries=0;
 enterAdmin=async()=>{window.adminEntries++};
 checkAccountAccess=async()=>{accountAccess={is_admin:true,role:'pt',session_valid:true};return accountAccess};
 loadCloudData=async()=>{window.accountEntries++};
 window.originalRpc=db.rpc;db.rpc=(name,args)=>name==='heartbeat'?{then:resolve=>Promise.resolve({data:null}).then(resolve)}:window.originalRpc(name,args);
 sessionStorage.removeItem('pitiLoginMode');
 activateSession({user:{id:'test'}});
`);
assert.equal(w.accountEntries,1);assert.equal(w.adminEntries,0);assert.equal(d.querySelector('#authBack').hidden,true);assert.equal(d.querySelector('#authError').textContent,'');
await w.testRun("sessionStorage.setItem('pitiLoginMode','admin');activateSession({user:{id:'test'}})");assert.equal(w.adminEntries,1);
await w.testRun("sessionStorage.removeItem('pitiLoginMode');activateSession({user:{id:'test'}})");assert.equal(w.accountEntries,2);
await w.testRun("enterAdmin=window.savedEnterAdmin;checkAccountAccess=window.savedCheck;loadCloudData=window.savedLoad;demoMode=true;adminMode=false;renderTestLauncher()");assert.ok(d.querySelector('#testUserLauncher'));
await w.testRun("demoMode=false;renderTestLauncher()");assert.equal(d.querySelector('#testUserLauncher'),null);
await w.testRun("authUser={id:'test'};accountAccess={is_admin:true,role:'pt'};enterAdmin()");assert.ok(d.querySelector('#mfaCode'));assert.equal(d.querySelector('#adminContent'),null);d.querySelector('#mfaCode').value='000000';await d.querySelector('#adminMfaGate form').onsubmit({preventDefault(){}});assert.equal(d.querySelector('#adminContent'),null);assert.equal(d.querySelector('#mfaError').textContent,'Yanlış kod');
d.querySelector('#mfaCode').value='123456';await d.querySelector('#adminMfaGate form').onsubmit({preventDefault(){}});assert.ok(d.querySelector('#adminContent'));assert.ok(d.querySelector('#adminContent').textContent.includes('Test <admin>'));assert.equal(d.querySelector('#adminContent admin'),null);assert.deepEqual(errors,[]);dom.window.close();console.log('PASS: login/register, exact DEMO visibility, MFA gate, admin list and escaped data');})().catch(e=>{console.error(e);process.exit(1)});
