-- Test-only snapshot of existing public schema, with a minimal auth.uid() shim.
create role anon nologin; create role authenticated nologin;
create schema auth; create table auth.users(id uuid primary key);
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
grant usage on schema auth,public to anon,authenticated;
grant execute on function auth.uid() to anon,authenticated;
create table public.clients (id uuid not null default gen_random_uuid(), pt_id uuid, user_id uuid, full_name text not null, phone text, email text, blood_type text, gender text, weight numeric(6,2), height numeric(6,2), archived boolean not null default false, created_at timestamp with time zone not null default now(), updated_at timestamp with time zone not null default now());
create table public.packages (id uuid not null default gen_random_uuid(), client_id uuid not null, name text not null default '12 Seans / 30 Gün'::text, price numeric(12,2) not null default 0, total_sessions integer, start_date date, expiry_date date, status text not null default 'active'::text, created_at timestamp with time zone not null default now());
create table public.sessions (id uuid not null default gen_random_uuid(), client_id uuid not null, pt_id uuid, starts_at timestamp with time zone not null, ends_at timestamp with time zone, status text not null default 'planned'::text, workout_title text, muscle_groups text[] not null default '{}'::text[], salon text, notes text, counts_against_package boolean not null default true, client_confirmed_at timestamp with time zone, created_at timestamp with time zone not null default now(), updated_at timestamp with time zone not null default now());
create table public.payments (id uuid not null default gen_random_uuid(), client_id uuid not null, package_id uuid, amount numeric(12,2) not null, method text, status text not null default 'pending'::text, receipt_path text, paid_at timestamp with time zone, created_at timestamp with time zone not null default now());
create table public.availability (id uuid not null default gen_random_uuid(), pt_id uuid, client_id uuid, starts_at timestamp with time zone not null, ends_at timestamp with time zone, all_day boolean not null default false, kind text not null default 'available'::text, note text, created_at timestamp with time zone not null default now());
create table public.profiles (id uuid not null, role text not null, full_name text not null, phone text, avatar_url text, created_at timestamp with time zone not null default now());
create table public.tasks (id uuid not null default gen_random_uuid(), client_id uuid not null, pt_id uuid, title text not null, due_at timestamp with time zone, status text not null default 'open'::text, result text, created_at timestamp with time zone not null default now());
create table public.messages (id uuid not null default gen_random_uuid(), client_id uuid not null, sender_id uuid, body text, attachment_path text, read_at timestamp with time zone, created_at timestamp with time zone not null default now());
alter table public.clients add constraint clients_pkey PRIMARY KEY (id);
alter table public.packages add constraint packages_pkey PRIMARY KEY (id);
alter table public.sessions add constraint sessions_pkey PRIMARY KEY (id);
alter table public.sessions add constraint sessions_status_check CHECK ((status = ANY (ARRAY['planned'::text, 'completed'::text, 'no_show'::text, 'cancelled'::text])));
alter table public.payments add constraint payments_pkey PRIMARY KEY (id);
alter table public.payments add constraint payments_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text])));
alter table public.availability add constraint availability_kind_check CHECK ((kind = ANY (ARRAY['available'::text, 'unavailable'::text, 'leave'::text, 'off'::text])));
alter table public.availability add constraint availability_pkey PRIMARY KEY (id);
alter table public.profiles add constraint profiles_full_name_check CHECK (((char_length(full_name) >= 1) AND (char_length(full_name) <= 160)));
alter table public.profiles add constraint profiles_pkey PRIMARY KEY (id);
alter table public.profiles add constraint profiles_role_check CHECK ((role = ANY (ARRAY['pt'::text, 'member'::text])));
alter table public.tasks add constraint tasks_pkey PRIMARY KEY (id);
alter table public.tasks add constraint tasks_status_check CHECK ((status = ANY (ARRAY['open'::text, 'done'::text, 'cancelled'::text])));
alter table public.messages add constraint messages_pkey PRIMARY KEY (id);
alter table public.clients add constraint clients_pt_id_fkey FOREIGN KEY (pt_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.clients add constraint clients_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.packages add constraint packages_client_id_fkey FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE;
alter table public.sessions add constraint sessions_client_id_fkey FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE;
alter table public.sessions add constraint sessions_pt_id_fkey FOREIGN KEY (pt_id) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.payments add constraint payments_client_id_fkey FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE;
alter table public.payments add constraint payments_package_id_fkey FOREIGN KEY (package_id) REFERENCES packages(id) ON DELETE SET NULL;
alter table public.availability add constraint availability_client_id_fkey FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE;
alter table public.availability add constraint availability_pt_id_fkey FOREIGN KEY (pt_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.profiles add constraint profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.tasks add constraint tasks_client_id_fkey FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE;
alter table public.tasks add constraint tasks_pt_id_fkey FOREIGN KEY (pt_id) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.messages add constraint messages_client_id_fkey FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE;
alter table public.messages add constraint messages_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.clients enable row level security;
alter table public.packages enable row level security;
alter table public.sessions enable row level security;
alter table public.payments enable row level security;
alter table public.availability enable row level security;
alter table public.profiles enable row level security;
alter table public.tasks enable row level security;
alter table public.messages enable row level security;
create policy profiles_read_self on public.profiles for select to authenticated using((select auth.uid())=id);
create policy profiles_create_self on public.profiles for insert to authenticated with check((select auth.uid())=id);
create policy profiles_edit_self on public.profiles for update to authenticated using((select auth.uid())=id) with check((select auth.uid())=id);

