const {test}=require('node:test');const assert=require('node:assert/strict');const vm=require('node:vm');const fs=require('node:fs');
const html=fs.readFileSync(require('node:path').join(__dirname,'../index.html'),'utf8');
const code=html.slice(html.indexOf('const clientHistoryKeys='),html.indexOf('let accountAccess=')).replace('captureClientInvite();','');
function setup(){const c={id:'manual-local',dbId:'stable-id',name:'Client',cloudManaged:true};const ctx={state:{role:'pt',customer:{id:'primary'},customerAccounts:{'manual-local':{package:{name:'Historical package'},progressData:[{w:90}],financeHistory:[{text:'Old payment'}]}}},clone:o=>JSON.parse(JSON.stringify(o)),Date,URL,sessionStorage:{getItem(){return ''}},document:{querySelector(){return null}},authUser:{id:'pt'},demoMode:false};ctx.state.ptProfile={name:'Mehmet Ağun'};ctx.state.events=[{id:1,customerId:c.id,type:'demo'},{id:2,customerId:'someone-else',type:'demo'}];vm.createContext(ctx);vm.runInContext(code,ctx);return {ctx,c};}
test('history includes existing package and measurements, excludes another client events',()=>{const {ctx,c}=setup();const payload=ctx.clientHistoryPayload(c);assert.equal(payload.package.name,'Historical package');assert.equal(payload.progressData[0].w,90);assert.equal(payload.extraEvents.length,1);assert.equal(payload.extraEvents[0].customerId,'stable-id');assert.equal(payload.memberTrainer.name,'Mehmet Ağun')});
test('manual customer status tracks pending, expired, revoked and linked states',()=>{const {ctx,c}=setup();assert.equal(ctx.clientLinkStatus(c),'Hesap açmadı');vm.runInContext("clientInvitations=[{client_id:'stable-id',expires_at:'2099-01-01'}]",ctx);assert.equal(ctx.clientLinkStatus(c),'Davet bekliyor');vm.runInContext("clientInvitations[0].revoked_at='2026-01-01'",ctx);assert.equal(ctx.clientLinkStatus(c),'Hesap açmadı');vm.runInContext("clientInvitations[0]={client_id:'stable-id',expires_at:'2000-01-01'}",ctx);assert.equal(ctx.clientLinkStatus(c),'Hesap açmadı');c.userId='member';assert.equal(ctx.clientLinkStatus(c),'Hesabı bağlı')});
test('sync uses version checking and skips unchanged history',async()=>{const {ctx,c}=setup();let calls=0;ctx.db={rpc:async(name,args)=>{calls++;assert.equal(name,'save_client_history');assert.equal(args.p_client_id,'stable-id');assert.equal(args.p_version,0);return {data:1}}};await ctx.syncClientHistories([c]);await ctx.syncClientHistories([c]);assert.equal(calls,1)});
test('failed history sync does not mark data as saved',async()=>{const {ctx,c}=setup();let calls=0;ctx.db={rpc:async()=>{calls++;return {error:Error('conflict')}}};await assert.rejects(ctx.syncClientHistories([c]),/conflict/);await assert.rejects(ctx.syncClientHistories([c]),/conflict/);assert.equal(calls,2)});
test('initials use current first and last name',()=>{const {ctx}=setup();assert.equal(ctx.profileInitials('Mehmet Ağun'),'MA');assert.equal(ctx.profileInitials('Ali Can İnce'),'Aİ')});
test('member history load restores the same customer history and supplementary events',async()=>{const {ctx,c}=setup();ctx.state.role='member';ctx.state.customer=c;ctx.state.manualCustomers=[];ctx.syncTestAccount=()=>{};ctx.db={from:()=>({select:async()=>({data:[{client_id:c.dbId,version:2,data:{package:{name:'Old package'},progressData:[{w:82}],extraEvents:[{id:99,type:'demo'}]}}]})})};await ctx.loadClientHistories();assert.equal(ctx.state.package.name,'Old package');assert.equal(ctx.state.progressData[0].w,82);assert.equal(ctx.state.events.find(e=>e.id===99).customerId,c.id)});
