const {JSDOM,VirtualConsole}=require(process.env.PITI_JSDOM_PATH||'jsdom'),fs=require('fs'),assert=require('assert/strict');
(async()=>{const html=fs.readFileSync('index.html','utf8').replace('<script src="/vendor/supabase.min.js"></script>','').replace('render();maybeOpenJoinLink();initAuth();','window.testRun=code=>eval(code);render();maybeOpenJoinLink();initAuth();');let verified=false;const errors=[],vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));const dom=new JSDOM(html,{url:'https://mypiti.online',runScripts:'dangerously',virtualConsole:vc,beforeParse(w){w.matchMedia=()=>({matches:false,addEventListener(){}});w.scrollTo=()=>{};w.supabase={createClient:()=>({auth:{onAuthStateChange(){},getSession:async()=>({data:{session:null}}),mfa:{getAuthenticatorAssuranceLevel:async()=>({data:{currentLevel:verified?'aal2':'aal1'}}),listFactors:async()=>({data:{totp:[{id:'test',status:'verified'}]}}),challengeAndVerify:async({code})=>code==='123456'?(verified=true,{data:{}}):{error:{message:'Yanlış kod'}}}},rpc:async(name,args)=>{if(name==='app_settings')return {data:{registration_open:true}};if(name==='admin_console'){if(args.p_action==='overview')return {data:{users:1,trainers:1,clients:0,online:1}};return {data:[{id:'test',full_name:'Test <admin>',username:'test',role:'pt',email:'test@example.invalid',created_at:new Date().toISOString(),is_admin:true}]}}return {data:null}}})}}});const w=dom.window,d=w.document;await new Promise(r=>setTimeout(r,20));

w.fixture=JSON.parse(fs.readFileSync('assets/demo-state.json','utf8'));w.testRun('demoMode=true;authUser=null;state=clone(window.fixture);render()');
assert.equal(w.testRun('financeCustomers().length'),10);assert.equal(w.testRun('Object.keys(state.customerAccounts).length'),10);
const events=JSON.parse(w.testRun('JSON.stringify(state.events.filter(e=>e.type==="session"))')).sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time));
for(let i=1;i<events.length;i++)assert.ok(events[i-1].date!==events[i].date||events[i-1].endTime<=events[i].time);
for(const c of w.fixture.demoCustomers){w.target=c.id;w.testRun("switchTestUser(window.target,'member','today')");assert.equal(w.testRun('state.customer.id'),c.id);assert.ok(d.querySelector('#liveMemberTasks'));w.testRun("nav('progress')");assert.ok(d.querySelector('#addMeasure'));}
w.testRun("switchTestUser(state.testPrimaryId,'pt','dashboard')");assert.equal(w.testRun('financeCustomers().length'),10);assert.equal(w.testRun('state.events.length'),w.fixture.events.length);assert.deepEqual(errors,[]);dom.window.close();console.log('PASS: realistic demo renders all clients without generating extra users or overlapping sessions');})().catch(e=>{console.error(e);process.exit(1)});
