const {JSDOM,VirtualConsole}=require(process.env.PITI_JSDOM_PATH||'jsdom');const fs=require('node:fs');const assert=require('node:assert/strict');
const html=fs.readFileSync(require('node:path').join(__dirname,'../index.html'),'utf8').replace(/<script src=[^>]+><\/script>/g,'').replace('render();maybeOpenJoinLink();initAuth();','window.testRun=code=>eval(code);render();maybeOpenJoinLink();initAuth();');
const pause=()=>new Promise(r=>setTimeout(r,30));
function setup({entry=false,required=false}={}){
 const errors=[],sent=[],virtualConsole=new VirtualConsole();virtualConsole.on('jsdomError',e=>errors.push(e.message));let session=null,mustChange=required;
 const pt={id:'pt-id',email:'pt@example.invalid'},member={id:'member-id',email:'member@example.invalid'};
 const records={profiles:[{id:pt.id,role:'pt',full_name:'Test PT'},{id:member.id,role:'member',full_name:'Test Member'}],clients:[{id:'client-one',pt_id:pt.id,user_id:member.id,full_name:'Client One',email:member.email},{id:'client-two',pt_id:pt.id,user_id:null,full_name:'Client Two',email:'two@example.invalid'}],sessions:[],client_invitations:[],account_audit:[],tasks:[],messages:[],client_history:[{client_id:'client-one',version:1,data:{package:null,payment:{status:'unpaid'},financeHistory:[],messages:[],tasks:[],progressData:[],unread:{pt:0,member:0},memberTrainer:{name:'Test PT',status:'connected'},extraEvents:[]}}]};
 const db={auth:{onAuthStateChange(){},async getSession(){return {data:{session}}},async signInWithPassword({email}){session={access_token:'mock-token',refresh_token:'mock-refresh',user:email===pt.email?pt:member};return {data:{session}}},async setSession(){session={access_token:'member-token',user:member};mustChange=true;return {data:{session}}},async signOut(){session=null;return {}}},async rpc(name,args){if(name==='get_my_trainer'){const c=records.clients.find(c=>c.user_id===session.user.id),p=records.profiles.find(p=>p.id===c?.pt_id);return {data:p?{client_id:c.id,id:p.id,name:p.full_name}:null}};if(name==='delete_archived_client'){const i=records.clients.findIndex(c=>c.id===args.p_client_id);if(i<0)return {error:{message:"Missing client"}};records.clients.splice(i,1);return {data:args.p_client_id}};if(name==='account_context')return {data:{session_valid:true,must_change_password:session.user.id===member.id&&mustChange,role:session.user.id===pt.id?'pt':'member'}};if(name==='save_client_history')return {data:2};return {data:[]}},from(table){let filters=[],operation='select',payload=null;const chain={select(){return this},order(){return this},limit(){return this},eq(k,v){filters.push(x=>x[k]===v);return this},in(k,v){filters.push(x=>v.includes(x[k]));return this},insert(v){operation='insert';payload=v;return this},upsert(v){operation='update';payload=v;return this},update(v){operation='update';payload=v;return this},async maybeSingle(){return {data:records[table].filter(x=>filters.every(f=>f(x)))[0]||null}},async single(){return this.maybeSingle()},then(resolve){let data=records[table].filter(x=>filters.every(f=>f(x)));if(operation==='insert'&&table==='messages'){sent.push(payload);records.messages.push({...payload,sender_role:session.user.id===pt.id?'pt':'member',created_at:new Date().toISOString(),read_at:null})}if(operation==='update'&&table==='messages')data.forEach(x=>Object.assign(x,payload));return Promise.resolve({data,error:null}).then(resolve)}};return chain}};
 const dom=new JSDOM(html,{url:'https://www.mypiti.online/'+(entry?'#entry='+'a'.repeat(64):''),runScripts:'dangerously',virtualConsole,beforeParse(w){w.supabase={createClient:()=>db};w.confirm=()=>true;w.scrollTo=()=>{};w.matchMedia=()=>({matches:false,addEventListener(){}});w.fetch=async(_,options)=>{const body=JSON.parse(options.body);if(body.action==='password'){mustChange=false;return new Response(JSON.stringify({success:true,relogin:true}),{status:200})}if(body.action==='redeem')return new Response(JSON.stringify({access_token:'member-token',refresh_token:'refresh'}),{status:200});throw Error('Unexpected mock action')}}});
 return {dom,sent,errors,records};
}

(async()=>{
 const h=setup(),w=h.dom.window,d=w.document;h.records.client_history=[];await pause();
 d.getElementById('authEmail').value='member@example.invalid';d.getElementById('authPassword').value='ValidPassword!';await d.getElementById('authForm').onsubmit({preventDefault(){}});
 assert.equal(w.testRun('state.memberTrainer.name'),'Test PT');w.testRun("nav('trainer')");assert.equal(d.getElementById('openClientClaim'),null);assert.ok(d.getElementById('openTrainerMessages'));
 d.getElementById('openTrainerMessages').click();await pause();assert.match(d.getElementById('view').textContent,/Test PT/);assert.doesNotMatch(d.getElementById('view').textContent,/Henüz PT bağlantısı yok/);assert.ok(d.getElementById('msgInput'));
 h.records.client_history=[{client_id:'client-one',version:1,data:{memberTrainer:{name:'Wrong trainer',status:'unlinked'}}}];await w.testRun('loadCloudData()');assert.equal(w.testRun('state.memberTrainer.name'),'Test PT');
 h.records.clients[0].pt_id=null;await w.testRun('loadCloudData()');w.testRun("nav('trainer')");assert.ok(d.getElementById('openClientClaim'));assert.equal(d.getElementById('openTrainerMessages'),null);assert.doesNotMatch(d.getElementById('view').textContent,/Wrong trainer/);
 assert.equal(h.errors.length,0,h.errors.join('\n'));h.dom.window.close();console.log('PASS: history-free first login, authoritative trainer name, stale history override, bound chat navigation, unlinked invitation retained');
})().catch(e=>{console.error(e);process.exit(1)});
