begin;
create temporary table tf(k text primary key,id uuid default gen_random_uuid(),sid uuid default gen_random_uuid());
insert into tf(k) values('oldpt'),('newpt'),('otherpt'),('member'),('othermember'),('client');
create temporary table tv(k text primary key,v jsonb);
grant all on tf,tv to authenticated;
insert into auth.users(id,email,email_confirmed_at,raw_app_meta_data,raw_user_meta_data)
select id,id::text||'@transfer-test.invalid',now(),jsonb_build_object('account_role',case when k like '%pt' then 'pt' else 'member' end),jsonb_build_object('full_name',k) from tf where k<>'client';
insert into auth.sessions(id,user_id,created_at,updated_at) select sid,id,now(),now() from tf where k<>'client';
update public.profiles set username='t_'||left(replace(id::text,'-',''),16) where id in (select id from tf where k='member');
insert into public.clients(id,pt_id,user_id,full_name) select c.id,p.id,m.id,'Transfer Member' from tf c,tf p,tf m where c.k='client' and p.k='oldpt' and m.k='member';
insert into public.client_history(client_id,data) select id,'{"progressData":[{"date":"2026-09-01","w":90}],"package":{"name":"OLD PACKAGE"},"payment":{"status":"approved","amount":500}}' from tf where k='client';
insert into public.sessions(client_id,pt_id,starts_at) select c.id,p.id,now()+interval '2 days' from tf c,tf p where c.k='client' and p.k='oldpt';
create function pg_temp.tid(key text) returns uuid language sql as $$select id from tf where k=key$$;
create function pg_temp.login(key text) returns text language sql as $$select set_config('request.jwt.claims',jsonb_build_object('sub',id,'session_id',sid,'role','authenticated','aal','aal1')::text,true) from tf where k=key$$;
create function pg_temp.ok(b boolean,label text) returns void language plpgsql as $$begin if b is distinct from true then raise exception 'FAIL: %',label;end if;end$$;
create function pg_temp.denied(q text,needle text) returns void language plpgsql as $$begin begin execute q;exception when others then if position(needle in sqlerrm)>0 then return;end if;raise;end;raise exception 'FAIL: expected rejection';end$$;
set local role authenticated;
select pg_temp.login('newpt');
insert into tv values('invite',public.trainer_transfer('create',jsonb_build_object('username','t_'||left(replace(pg_temp.tid('member')::text,'-',''),16))));
select pg_temp.login('othermember');
select pg_temp.denied(format('select public.trainer_transfer(''preview'',%L::jsonb)',jsonb_build_object('code',(select v->>'code' from tv where k='invite'))),'başka hesaba');
select pg_temp.login('member');
insert into tv values('preview',public.trainer_transfer('preview',jsonb_build_object('code',(select v->>'code' from tv where k='invite'))));
select pg_temp.ok((select (v->>'future_sessions')::integer=1 from tv where k='preview'),'future cancellation shown');
select pg_temp.denied(format('select public.trainer_transfer(''accept'',%L::jsonb)',(select v||jsonb_build_object('code',(select v->>'code' from tv where k='invite'),'confirmed',false) from tv where k='preview')),'onayla');
select pg_temp.denied(format('select public.trainer_transfer(''accept'',%L::jsonb)',(select v||jsonb_build_object('code',(select v->>'code' from tv where k='invite'),'confirmed',true,'fingerprint','stale') from tv where k='preview')),'Bilgiler değişmiş');
insert into tv values('accepted',public.trainer_transfer('accept',(select v||jsonb_build_object('code',(select v->>'code' from tv where k='invite'),'confirmed',true,'share_measurements',false) from tv where k='preview')));
select pg_temp.ok((select count(*)=1 from public.clients where user_id=auth.uid() and pt_id=pg_temp.tid('newpt')),'new active relationship');
select pg_temp.ok((select count(*)=1 from public.trainer_transfers where member_id=auth.uid() and snapshot#>>'{history,package,name}'='OLD PACKAGE'),'member retained former history');
select pg_temp.ok((select data->'progressData'='[]'::jsonb and not data ? 'package' from public.client_history where client_id=(select (v->>'client_id')::uuid from tv where k='accepted')),'no implicit measurements or package transfer');
select pg_temp.denied(format('insert into public.account_state(user_id,data) values(auth.uid(),%L::jsonb)',jsonb_build_object('customer',jsonb_build_object('dbId',pg_temp.tid('client')))),'PT bağlantısı değişti');
select pg_temp.denied(format('select public.trainer_transfer(''accept'',%L::jsonb)',(select v||jsonb_build_object('code',(select v->>'code' from tv where k='invite'),'confirmed',true) from tv where k='preview')),'Davet geçersiz');
select pg_temp.login('oldpt');
select pg_temp.ok((select count(*)=1 from public.transfer_notifications where recipient_id=auth.uid()),'former PT informed without approval');
select pg_temp.ok((select count(*)=0 from public.clients where id=(select (v->>'client_id')::uuid from tv where k='accepted')),'former PT cannot see new relationship');
select pg_temp.ok((select count(*)=1 from public.sessions where client_id=pg_temp.tid('client') and status='cancelled'),'future old session cancelled');
select pg_temp.denied('update public.clients set archived=false where id=pg_temp.tid(''client'')','salt okunur');
select pg_temp.denied('update public.sessions set notes=''stale'' where client_id=pg_temp.tid(''client'')','salt okunur');
select pg_temp.denied('select public.save_client_history(pg_temp.tid(''client''),''{}'',1)','salt okunur');
select public.trainer_transfer('ack',jsonb_build_object('id',(select id from public.transfer_notifications limit 1)));
select pg_temp.ok((select bool_and(read_at is not null) from public.transfer_notifications),'notice acknowledged');
select pg_temp.login('newpt');
select pg_temp.ok((select count(*)=0 from public.client_history where client_id=pg_temp.tid('client')),'new PT cannot read old history');
select pg_temp.ok((select count(*)=0 from public.trainer_transfers),'new PT cannot read member snapshot');
select pg_temp.login('otherpt');
select pg_temp.ok((select count(*)=0 from public.transfer_notifications),'other PT no notifications');
select pg_temp.ok((select count(*)=0 from public.trainer_transfers),'other PT no snapshots');
reset role;
select 'PASS: member consent, no former-PT approval, notification, session cancellation, independent history, stale writes and cross-PT isolation' result;
rollback;
